MiPrimeraAppMVC/MiPrimeraAppMVC/Models/ErrorViewModel.cs
namespace MiPrimeraAppMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MiPrimeraAppMVC/MiPrimeraAppMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MiPrimeraAppMVC.Models;

namespace MiPrimeraAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MiPrimeraAppMVC/MiPrimeraAppMVC/Controllers/LaboratorioController.cs
using CapaDatos;
using CapaEntidad;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAppMVC.Controllers
{
    public class LaboratorioController : Controller
    {
        // GET: LaboratorioController
        public ActionResult Index()
        {
            return View();
        }

        public List<LaboratorioCLS> listarLaboratorios()
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.listarLaboratorios();
        }

        public List<LaboratorioCLS> filtrarLaboratorios(LaboratorioCLS objLaboratorio)
        {
            LaboratorioDAL obj = new LaboratorioDAL();
            return obj.filtrarLaboratorios(objLaboratorio);
        }

        public string cadena()
        {
            IConfigurationBuilder builder = new ConfigurationBuilder();
            builder.AddJsonFile(Path.Combine(Directory.GetCurrentDirectory(), "appsettings.json"));
            var root = builder.Build();
            var cadenaDato = root.GetConnectionString("cn");
            return cadenaDato;
        }
    }
}

MiPrimeraAppMVC/MiPrimeraAppMVC/Controllers/MedicamentoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAppMVC.Controllers
{
    public class MedicamentoController : Controller
    {
        // GET: MedicamentoController
        public ActionResult Index()
        {
            return View();
        }

        // GET: MedicamentoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MedicamentoController/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: MedicamentoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicamentoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MedicamentoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MedicamentoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MedicamentoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MiPrimeraAppMVC/MiPrimeraAppMVC/Controllers/SucursalController.cs
using CapaDatos;
using CapaEntidad;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAppMVC.Controllers
{
    public class SucursalController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public List<SucursalCLS> listarSucursales()
        {
            SucursalDAL obj = new SucursalDAL();
            return obj.listarSucursales();
        }

        public List<SucursalCLS> filtrarSucursales(SucursalCLS objSucursal)
        {
            SucursalDAL obj = new SucursalDAL();
            return obj.filtrarSucursales(objSucursal);
        }

        public string cadena()
        {
            IConfigurationBuilder builder = new ConfigurationBuilder();
            builder.AddJsonFile(Path.Combine(Directory.GetCurrentDirectory(), "appsettings.json"));
            var root = builder.Build();
            var cadenaDato = root.GetConnectionString("cn");
            return cadenaDato;
        }

    }
}

MiPrimeraAppMVC/MiPrimeraAppMVC/Controllers/TipoMedicamentoController.cs
using CapaDatos;
using CapaEntidad;
using CapaNegocios;
using Microsoft.AspNetCore.Mvc;

namespace MiPrimeraAppMVC.Controllers
{
    public class TipoMedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Inicio() {
            return View();
        }
        public IActionResult SinMenu() {
            return View();
        }

        public List<TipoMedicamentoCLS> listarTipoMedicamento()
        {
            TipoMedicamentoDAL obj = new TipoMedicamentoDAL();
            return obj.listarTipoMedicamento();
        }

        public List<TipoMedicamentoCLS> filtrarTipoMedicamento(string nombre)
        {
            TipoMedicamentoDAL obj = new TipoMedicamentoDAL();
            return obj.filtrarTipoMedicamento(nombre);
        }

        public string cadena(){
            IConfigurationBuilder builder = new ConfigurationBuilder();
            builder.AddJsonFile(Path.Combine(Directory.GetCurrentDirectory(), "appsettings.json"));
            var root = builder.Build();
            var cadenaDato = root.GetConnectionString("cn");
            return cadenaDato;
        }

    }
}

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/Laboratorio/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Laboratorio</h1>

<fieldset>
    <form id="frmBusqueda" method="post" class="row g-3">
        <div class="col-md-6">
            <label for="name" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="inputNombre" placeholder="Nombre">
        </div>
        <div class="col-md-6">
            <label for="Direccion" class="form-label">Direccion</label>
            <input type="text" class="form-control" name="Direccion" id="inputDireccion" placeholder="Direccion">
        </div>
        <div class="col-12">
            <label for="personaContacto" class="form-label">Persona Contacto</label>
            <input type="text" class="form-control" id="inputPersona" name="personaContacto">
        </div>
        <div class="col-12">
            <button type="button" class="btn btn-success" onclick="BuscarLaboratorio()">Buscar</button>
            <button type="button" class="btn btn-danger" onclick="LimpiarLaboratorio()">Limpiar</button>

        </div>
    </form>

</fieldset>

<div id="divTable">
</div>

<script src="~/js/generico.js"></script>
<script src="~/js/laboratorio.js"></script>

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/Medicamento/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Medicamento</h1>

<div id="divTable">
</div>

<script src="~/js/generico.js"></script>
<script src="~/js/medicamento.js"></script>

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiPrimeraAppMVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiPrimeraAppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiPrimeraAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoMedicamento" asp-action="Index">Tipo Medicamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoMedicamento" asp-action="SinMenu">Sin Menú</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sucursal" asp-action="Index">Sucursal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratorio" asp-action="Index">Laboratorio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MiPrimeraAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/Sucursal/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Sucursal</h1>

<fieldset>
    <form id="frmBusqueda" method="post" class="row g-3">
        <div class="col-md-6">
            <label for="nombre" class="form-label">Nombre Sucursal</label>
            <input type="text" class="form-control" name="nombre" id="inputNombre">
        </div>
        <div class="col-md-6">
            <label for="direccion" class="form-label">Direccion</label>
            <input type="text" class="form-control" name="direccion" id="inputNombre">
        </div>
        <div class="col-12">
            <button type="button" class="btn btn-success" onclick="BuscarSucursales()">Buscar</button>
            <button type="button" class="btn btn-danger" onclick="LimpiarSucursales()">Limpiar</button>
        </div>
    </form>

</fieldset>

<div id="divTable">

</div>

<script src="~/js/generico.js"></script>
<script src="~/js/sucursal.js"></script>

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/TipoMedicamento/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Tipo Medicamento</h1>

<div class="input-group">
    <input id="txtTipoMedicamento" type="text" class="form-control" onkeyup="filtarTipoMedicamento()" placeholder="Ingresar tipo medicamento a buscar" aria-label="Recipient's username with two button addons">
    
</div>

<div id="divTable">

</div>

<script src="~/js/generico.js"></script>
<script src="~/js/tipoMedicamento.js"></script>

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/TipoMedicamento/Inicio.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<h1>Inicio</h1>

MiPrimeraAppMVC/MiPrimeraAppMVC/Views/TipoMedicamento/SinMenu.cshtml
@{
    ViewData["Title"] = "Index";
}

<div id="divTable">
</div>

<script src="~/js/generico.js"></script>
<script src="~/js/tipoMedicamento.js"></script>